version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - mynet
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/postgresql/data
  undian:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - mynet
    volumes:
      - /etc/localtime:/etc/localtime:ro
networks:
  mynet:
    external: true
    name: proxy_net
